# Generated by Django 4.0.5 on 2022-06-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_drink_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drink',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
