# Generated by Django 4.0.5 on 2022-06-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_drink_product_alter_product_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='drink',
            new_name='products',
        ),
    ]
