# Generated by Django 4.0.5 on 2022-06-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_drink_image_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='drink',
            new_name='product',
        ),
    ]
