# Generated by Django 4.0.5 on 2022-06-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_drink_allergy_drink_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='drink',
            new_name='product',
        ),
    ]
