# Generated by Django 4.0.5 on 2022-06-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_drink_nutrition_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergy_Drink',
            new_name='Allergy_Product',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='products',
            new_name='prod',
        ),
        migrations.AlterModelTable(
            name='allergy_product',
            table='allergy_products',
        ),
    ]
