# Generated by Django 4.0.5 on 2022-06-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_allergy_drink_allergy_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='prod',
            new_name='product',
        ),
    ]
